# Generated by Django 4.0.1 on 2022-01-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Pcpoint', '0002_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='Password',
            new_name='password',
        ),
        migrations.AddField(
            model_name='signup',
            name='usertype',
            field=models.CharField(default='customer', max_length=100),
        ),
    ]
