# Generated by Django 4.0.1 on 2022-01-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Pcpoint', '0004_addproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
