# Generated by Django 4.0.1 on 2022-02-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Pcpoint', '0008_carts_price_carts_qty_carts_status_carts_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carts',
            name='totalprice',
            field=models.CharField(max_length=100),
        ),
    ]
