# Generated by Django 4.0.1 on 2022-02-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Pcpoint', '0009_alter_carts_price_alter_carts_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='carts',
            name='totalprice',
            field=models.IntegerField(default=1),
        ),
    ]
