# Generated by Django 4.0.1 on 2022-02-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Pcpoint', '0010_alter_carts_price_alter_carts_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='carts',
            name='totalprice',
            field=models.CharField(max_length=10),
        ),
    ]
