# Generated by Django 4.0.1 on 2022-02-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Pcpoint', '0013_alter_addproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carts',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carts',
            name='totalprice',
            field=models.IntegerField(),
        ),
    ]
